### PR TITLE
removing bamboo bundle to be moved to bamboo rather than here

### PR DESCRIPTION
**Pull request by cordoval**
|Q            |A  |
|---          |---|
|Bug Fix?     |no |
|New Feature? |no |
|BC Breaks?   |no |
|Deprecations?|no |
|Tests Pass?  |yes |
|Fixed Tickets| #650  |
|License      |MIT|

### CODE REVIEW

**Comment by mmoreram** [comment]
Yes, well, once this Bundle is deleted from this repository, should be placed into another one, right? We still have to think where we should place this repo.

ASAP we know that, I will rebase&merge this ;)

Thanks.

**Comment by mmoreram** [comment]
@cordoval Can you rebase please, in order to accept it? Thanks :)

**Comment by cordoval** [comment]
bump @mmoreram

**Comment by mmoreram** [comment]
Thanks @cordoval

**Pull request merged**
