### PR TITLE
added removeProduct function in CartManager

### PR DESCRIPTION
**Pull request by claretcrab**
I think it's usefull if you don't know the cartLine ID but you know product ID

### CODE REVIEW

**Comment by alch** [comment]
Why not change `addProduct` so that it can accept a *negative* value (the inner method `Cartmanager::setCartLineQuantity` already checks that the final quantity is > 0 and if not it *removes* the product from the cart) ?

Then the `CartManager::removeProduct` would be something like

```php
public function removeProduct(
        CartInterface $cart,
        PurchasableInterface $purchasable,
        $quantity
) {
    return $this->addProduct($cart, $purchasable, -$quantity);
}
```

Opinions?

**Comment by xphere** [comment]
I found quite counterintuitive that `addProduct` accepts a negative amount in quantity…
I'd rather move the `<= 0` check to `removeProduct` and throw when `addProduct` receives negative quantity.

**Comment by claretcrab** [comment]
Mmmm i think it's better to have different methods for this purpose, because in addProduct there is the logic of addLine too.

**Comment by claretcrab** [comment]
unit test added

**Comment by alch** [comment]
:+1:

**Pull request merged**
