### PR TITLE
usage of directors

### PR DESCRIPTION
**Pull request by cordoval**
|Q            |A  |
|---          |---|
|Bug Fix?     |no |
|New Feature? |no |
|BC Breaks?   |no |
|Deprecations?|no |
|Tests Pass?  |no |
|Fixed Tickets| #646  |
|License      |MIT|
                   
This is depending on https://github.com/elcodi/elcodi/pull/664 to be merged first.

### CODE REVIEW

**Comment by mmoreram** [comment]
@cordoval Is that ready?

**Comment by cordoval** [comment]
not yet, it is a [WIP]. It needs rebasing on its dependent PR that now it is merged but it bootstrap other changes. I will continue to work on this here and update accordingly.

**Comment by cordoval** [comment]
@mmoreram i will rebase now and finish this to make tests pass

**Comment by mmoreram** [comment]
@cordoval Great :D

**Comment by mmoreram** [comment]
@cordoval BTW, what do U think about this new concept? Very useful for tests and fixtures, right? :dancer:

**Comment by cordoval** [comment]
it does save lines and some boilerplate. Ok ready cc @mmoreram

**Comment by cordoval** [comment]
bump @mmoreram

**Pull request merged**
