### PR TITLE
refactor to single router loader

### PR DESCRIPTION
**Pull request by cordoval**
|Q            |A   |
|---          |--- |
|Bug Fix?     |no  |
|New Feature? |yes |
|BC Breaks?   |no  |
|Deprecations?|no  |
|Tests Pass?  |yes |
|Fixed Tickets|#364|
|License      |MIT |

### CODE REVIEW

**Comment by xphere** [comment]
Nice! Maybe [this other router in `Page` component](https://github.com/elcodi/elcodi/blob/master/src/Elcodi/Bundle/PageBundle/Resources/config/loaders.yml#L6) may face the same fortune… :wink:

**Comment by cordoval** [comment]
@mmoreram the tests pass on lowest dependencies, but they don't on later dependencies https://github.com/doctrine/doctrine2/blob/2.5/lib/Doctrine/ORM/EntityNotFoundException.php and other changes in doctrine upstream i believe. This should be addressed in another PR. This is however good to merge as the failing is unrelated.

**Comment by mmoreram** [comment]
Can you rebase please?

**Comment by mmoreram** [comment]
* Because we're moving to a non `.class` usage, could you please remove that one?
* Why do you place the files in the Bundle? Remember, all non-framework-dependent classes in the component

**Comment by cordoval** [comment]
I will rebase @mmoreram 
Re: location, i will just move it, to me is not really important or i don't see much difference
Re: 3rd bullet, can we do that in another consecutive PR? after this one is merged?

**Comment by mmoreram** [comment]
@cordoval (3rd bullet) Of course we can, is something I would like to discuss about.

**Comment by cordoval** [comment]
@mmoreram done :older_man:

**Comment by cordoval** [comment]
bump @mmoreram

**Comment by cordoval** [comment]
rebased @mmoreram

**Comment by cordoval** [comment]
this is ready @mmoreram

**Comment by mmoreram** [comment]
Nopes. You are introducing again all `classes.yml` file. Can you please fix this please? Txs!

**Comment by cordoval** [comment]
ok i will rebase @mmoreram good catch, actually this was before the other PR was merged, that is why, but fixing now

**Comment by cordoval** [comment]
@mmoreram ahora si :older_man:

**Pull request merged**
