### PR TITLE
Fixed product amount in CartLine

### PR DESCRIPTION
**Pull request by alch**
* CartLine `product_amount` is now set as **product unit price**
* CartLine `amount` is `product_amount` * `quantity`

### CODE REVIEW

**Comment by alch** [comment]
References https://github.com/elcodi/bamboo/issues/191

Ping @seventhseeker

**Comment by mmoreram** [comment]
@alch Thanks for the change :) This feature should be tested, so I merge but I will not close the issue in Order to remind us the need of testing :)

**Comment by alch** [comment]
Ping @elcodi/owners Ok to merge? Would like a review on this, although tests are passing

**Comment by mmoreram** [comment]
@alch Merged

**Comment by alch** [comment]
:+1:

**Pull request merged**
