### PR TITLE
Fixed api locations route

### PR DESCRIPTION
**Pull request by rogergros**
Fixed url for locations API

Related with https://github.com/elcodi/bamboo/pull/338

### CODE REVIEW

**Comment by mmoreram** [comment]
This is not good at all, because you are using `%bamboo_api_prefix%`, and this is a Bamboo parameter...

**Comment by cordoval** [comment]
can we make it a config param of the bundle that can be defined via the configuration of the bundle?

**Comment by cordoval** [comment]
This is what i mean #721 @mmoreram

**Comment by rogergros** [comment]
Woops, right, the thing is that this is now broken.

We can simply close it, the think is that we have a **%bamboo_api_prefix%** that's used nowhere with this PR https://github.com/elcodi/bamboo/pull/338/files

**Pull request closed without merging**
