### PR TITLE
[WIP] media create image on resize

### PR DESCRIPTION
**Pull request by cordoval**
|Q            |A   |
|---          |--- |
|Bug Fix?     |no  |
|New Feature? |no  |
|BC Breaks?   |no  |
|Deprecations?|no  |
|Tests Pass?  |no  |
|Fixed Tickets|#521|
|License      |MIT |

### CODE REVIEW

**Comment by mmoreram** [comment]
@cordoval Do you think is necessary a new entity for that?

About your question, we're using collections in entities. What we don't want to couple is entities and any collection implementation, like ArrayCollection.

**Comment by xphere** [comment]
This is related to a discussion we're having in #521, but we have not yet reached an agreement.

**Comment by cordoval** [comment]
@xphere in FOSS we use the table PR as in this PR description to display the ticket that is related to. Maybe you are using a client for github?  but if you are on this page to see the discussion this is already in the description of the PR so right. And correct we haven't reached an agreement, just exploring the idea publicly to see what roadblocks we encounter.

**Comment by xphere** [comment]
Yep, just pointing to the discussion in another thread, hoping for some additional visibility.

**Comment by cordoval** [comment]
:+1:

**Comment by mmoreram** [comment]
I don't think that a new table for such feature is a good idea. In such table won't be relevant information indeed. Maybe I don't understand properly the implementation, but I think that, as said in #521, a new service overwriting the manager would be enough.

**Pull request closed without merging**
