### PR TITLE
Readme: Refer to Symfony2 as Symfony and update Bamboo link

### PR DESCRIPTION
**Pull request by hacfi**

### CODE REVIEW

**Comment by alch** [comment]
I think it's `in crescendo` (in the context of growing dynamics in music, see [here](http://en.wikipedia.org/wiki/Dynamics_(music)#Gradual_changes))

**Comment by hacfi** [comment]
Alright..get it now.

**Comment by hacfi** [comment]
The description of the repo also contains symfony2 - should be renamed to "E-commerce components for Symfony"

**Comment by mmoreram** [comment]
@hacfi Great! I'll do it right now :D Thanks!

**Comment by hacfi** [comment]
Only thing left to do is change the GitHub repository description to "E-commerce components for Symfony".

**Comment by mmoreram** [comment]
@hacfi Done! Thanks :)

**Comment by hacfi** [comment]
Perfect! Hopefully getting my Macbook back today so I can continue my review.

**Pull request merged**
