### PR TITLE
move out fixtures booster bundle to friends-of-el-codi

### PR DESCRIPTION
**Pull request by cordoval**
|Q            |A  |
|---          |---|
|Bug Fix?     |no |
|New Feature? |no |
|BC Breaks?   |no |
|Deprecations?|no |
|Tests Pass?  |no |
|Fixed Tickets|  #656 |
|License      |MIT|

### CODE REVIEW

**Comment by cordoval** [comment]
@mmoreram i cannot make this green if you don't move the repo code to friends-of-elcodi please

**Comment by cordoval** [comment]
@mmoreram rebased!

**Comment by cordoval** [comment]
@mmoreram ping

**Comment by mmoreram** [comment]
We'll finally use `elcodi/elcodi` as a single repository in order to focus in one repo all business logic. I will close all related opened PRs.

Thanks @cordoval

**Comment by cordoval** [comment]
:cry: ok, but at least early feedback could have prevented me to focus on those things since that is not going to be the direction.

**Comment by mmoreram** [comment]
well, this decision only prevent us of removing 3 packages. This is no so much indeed, and this idea was just moving around my head, so nothing was decided at all...

**Pull request closed without merging**
