### PR TITLE
Some small changes

### PR DESCRIPTION
**Pull request by mmoreram**
This branch contains some small changes. One of them is several new entity tests. Related to #1038

* For CartCoupon component
* For Comment component

This also fixes these issues

* https://github.com/elcodi/elcodi/issues/1050

### CODE REVIEW

**Comment by EmanueleMinotto** [comment]
Why is the phpunit dependency fixed to a specific minor and patch?

**Comment by mmoreram** [comment]
Well, as it's always been. If tests run green with a specific version of PHPUnit, I don't see a reason to let PHPUnit be updated as much as it can (avoiding that way possible errors from the maintainers in new versions)

**Comment by mmoreram** [comment]
ping @EmanueleMinotto

**Comment by EmanueleMinotto** [comment]
imo allowing (at least) the patch part could prevent us, in the future, to investigate on problems those could be related to phpunit and not to elcodi

**Comment by mmoreram** [comment]
Due to some discussions between @EmanueleMinotto and me in our [Gitter channel](https://gitter.im/elcodi/elcodi), we merge this PR and we will discuss about these PHPUnit issue in another thread :+1:

**Pull request merged**
