### PR TITLE
Removed ReferralProgram Bundle and Component

### PR DESCRIPTION
**Pull request by mmoreram**
* Because both are not complying desired code standards and need some love and refactoring, these
packages are removed with the desire of adding them back as plugin

### CODE REVIEW

**Comment by mmoreram** [comment]
ping @elcodi/deciders

**Comment by xphere** [comment]
I'm :+1: on this since the first minute I joined the Elcodi team. :grin:
cof cof plugin cof cof

**Comment by alch** [comment]
Ping @claretcrab

**Comment by claretcrab** [comment]
:+1: we already talk with Marc and it's ok, if we need this feature we will implement it as a plugin for deliberry based on this removed code

**Pull request merged**
