### PR TITLE
Issuse #921 All events set final classes

### PR DESCRIPTION
**Pull request by mmoreram**
* This change introduces BC Break somehow, only for people that have extended elcodi
  events.
* This binds the domain events, and protects it for extension

### CODE REVIEW

**Comment by jontorrado** [comment]
What is the reason for protecting domain events?

**Comment by theofidry** [comment]
immutability and final classes just :heart:

**Comment by mmoreram** [comment]
@jontorrado We want to prevent anyone extending our domain events. No one should use them indeed, they should only be created in our event dispatchers.

**Comment by mmoreram** [comment]
@EmanueleMinotto do I have your approval with this? :dancers:

**Comment by EmanueleMinotto** [comment]
@mmoreram yes, after the explanation on Gitter this is ok for me too :+1:

**Pull request merged**
