### PR TITLE
Removed property and access methods

### PR DESCRIPTION
**Pull request by mmoreram**
Non-used property is removed

### CODE REVIEW

**Comment by mmoreram** [comment]
@rogergros @alch @xphere Can you please confirm that this property is not really used anywhere?

**Comment by rogergros** [comment]
When was this created? :neutral_face: we have a "billingAddress" on cart that should be converted on the Cart to Order transformation process. 

Right now we are not generating invoices but in a future this will be needed to generate it, isn't it?

**Comment by mmoreram** [comment]
@rogergros Yes, but for that we have TaxAddress, right?

**Comment by rogergros** [comment]
@mmoreram Yes, that seems to be the case. Then it's ok for me :+1:

**Comment by cordoval** [comment]
you still need to remove the methods in the interface:

```bash
...........PHP Fatal error:  Class Elcodi\Component\Cart\Entity\Order contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Elcodi\Component\Cart\Entity\Interfaces\OrderInterface::getInvoiceAddress, Elcodi\Component\Cart\Entity\Interfaces\OrderInterface::setInvoiceAddress) in /home/travis/build/elcodi/elcodi/src/Elcodi/Component/Cart/Entity/Order.php on line 461
```

**Comment by mmoreram** [comment]
Working on that ATM

**Comment by cordoval** [comment]
:+1:

**Pull request merged**
