### PR TITLE
Added configuration for payment methods

### PR DESCRIPTION
**Pull request by alch**

### CODE REVIEW

**Comment by xphere** [comment]
I wonder why this can't go in it's own `configuration.yml` file…

**Comment by alch** [comment]
@xphere I couldn't fond a way to merge these values to the ’condiguration.yml’ on bamboobundle. This is the config tree of ’ElcodiConfigurationBundle’. Any ideas?

**Comment by xphere** [comment]
This is just loaded in `app/config.yml`, just add a `configuration.yml` file in your bundle and load it before the default one. Even adding to `config_local.yml` in this case. Would that work?

**Comment by alch** [comment]
@xphere solved with this https://github.com/elcodi/elcodi/commit/e4621c93a575b44df0d850b300b1fb26fa6b4391

It looks like the lack of the `useAttributeAsKey()` method was necessary in order to thh configuration to be merged properly

Closing

**Comment by xphere** [comment]
:clap::clap::clap:

**Pull request closed without merging**
