### PR TITLE
Replace elcodi:~0.5.0 to elcodi:self.version

### PR DESCRIPTION
**Pull request by xphere**
Could something like this make sense? /ping @mmoreram 

This fixes a bug with `--prefer-lowest` when requiring a bundle `0.5.18` installs the component `0.5.0`.

### CODE REVIEW

**Comment by mmoreram** [comment]
Using this strategy, when your code is not on any version, then I think that `dev-master` is used instead.

**Comment by xphere** [comment]
This is not using the root package version, but the root dependency to locate the underneath versions.
So, if your application depends on `elcodi/product-bundle: 0.5.17` and `elcodi/tax-bundle: 0.5.12`, you're depending also on `elcodi/product: 0.5.17` and `elcodi/tax: 0.5.12`.

**Comment by xphere** [comment]
The problem is I don't know if we can enforce this retroactively to our old tags.

**Comment by mmoreram** [comment]
Each version of Elcodi should only depend only on these versions that can be compatible with. Old versions of all packages are this. Old.

As soon as Elcodi reaches a `stable` version, then you can use the `^` element. Since this moment, old tags are wrong.

**Comment by xphere** [comment]
Ok, so this makes sense only after reaching the 1.0 milestone. Makes sense.

**Pull request closed without merging**
