### PR TITLE
[Plugin] Check if plugin really exists before load routing information related to #981

### PR DESCRIPTION
**Pull request by miguelvilata**
Another PR will be necessary to fix 981 issue itself.

### CODE REVIEW

**Comment by EmanueleMinotto** [comment]
thanks @miguelvilata for this PR :)
can you fix the coding style (using the `composer check-style` command) and squash the commits, please?

**Comment by mmoreram** [comment]
Thanks @miguelvilata 
I will check this PR during this weekend :dancer: 
Great work dude! I hope this is the first of many and many accepted PRs from you!

:)

**Comment by miguelvilata** [comment]
Thanks you for your help. I tried to pass coding style but the tool changed other files than the I changed for the PR, and I'm not sure what to do in this case.

I'll check again on monday.

**Comment by EmanueleMinotto** [comment]
@miguelvilata commands should be:

``` bash
php vendor/bin/php-cs-fixer fix --config-file=.php_cs src/Elcodi/Component/Plugin/Entity/Plugin.php
php vendor/bin/php-cs-fixer fix --config-file=.php_cs src/Elcodi/Component/Plugin/Exception/PluginNotFoundException.php
php vendor/bin/php-cs-fixer fix --config-file=.php_cs src/Elcodi/Component/Plugin/Loader/RouterLoader.php
php vendor/bin/php-cs-fixer fix --config-file=.php_cs src/Elcodi/Component/Plugin/Tests/Entity/PluginTest.php
php vendor/bin/php-formatter f:h:f src/Elcodi/Component/Plugin/Entity/Plugin.php
php vendor/bin/php-formatter f:h:f src/Elcodi/Component/Plugin/Exception/PluginNotFoundException.php
php vendor/bin/php-formatter f:h:f src/Elcodi/Component/Plugin/Loader/RouterLoader.php
php vendor/bin/php-formatter f:h:f src/Elcodi/Component/Plugin/Tests/Entity/PluginTest.php
php vendor/bin/php-formatter f:u:s src/Elcodi/Component/Plugin/Entity/Plugin.php
php vendor/bin/php-formatter f:u:s src/Elcodi/Component/Plugin/Exception/PluginNotFoundException.php
php vendor/bin/php-formatter f:u:s src/Elcodi/Component/Plugin/Loader/RouterLoader.php
php vendor/bin/php-formatter f:u:s src/Elcodi/Component/Plugin/Tests/Entity/PluginTest.php
```

and after them a `git rebase` :)

**Comment by miguelvilata** [comment]
It looks like there is a problem with a missing table in Travis, could you check it please?

**Comment by mmoreram** [comment]
Closing in favor of #1058

**Pull request closed without merging**
