### PR TITLE
appveyor configuration & badge

### PR DESCRIPTION
**Pull request by EmanueleMinotto**
Ref: https://github.com/elcodi/elcodi/issues/927

### CODE REVIEW

**Comment by mmoreram** [comment]
https://ci.appveyor.com/project/mmoreram/elcodi/build/1.0.1

**Comment by mmoreram** [comment]
@EmanueleMinotto I merged the PR you did before about skipping ImageMagick tests if is not installed.

Rebase with master and let's wait again :)

Thanks man!

**Comment by EmanueleMinotto** [comment]
@mmoreram PR rebased, now it works :)

**Comment by mmoreram** [comment]
@EmanueleMinotto Great :dancer: 

Amazing dude... a-ma-zing :)

**Pull request merged**
