### PR TITLE
Adding configuration comp+bundle deprecation

### PR DESCRIPTION
**Pull request by mmoreram**

### CODE REVIEW

**Comment by mmoreram** [comment]
Solves #988

**Comment by mmoreram** [comment]
ping @EmanueleMinotto

**Comment by EmanueleMinotto** [comment]
Shouldn't the Configuration component trigger an error too?

**Comment by mmoreram** [comment]
Yes, but it is a component... should we add this in all classes?

**Comment by EmanueleMinotto** [comment]
Uhm no... probably marking the package on packagist.org would be enough :)

**Comment by mmoreram** [comment]
Yes, I will mark them all as abandoned right now :)

**Comment by EmanueleMinotto** [comment]
great, well done than :+1:

**Comment by mmoreram** [comment]
Done!

**Pull request merged**
