### PR TITLE
remove extra framework bundle dependency

### PR DESCRIPTION
**Pull request by cordoval**
|Q            |A   |
|---          |--- |
|Fixed Tickets|#725|
                    

remove framework extra bundle dependency

### CODE REVIEW

**Comment by mmoreram** [comment]
@cordoval Could you please move this PR to Bamboo? :)

Sorry for this! :(

**Comment by cordoval** [comment]
sure thing with the aid of gush all things are possible cc @sstok :wine_glass:

**Comment by sstok** [comment]
Moving a pull-request :) thats not supported yet, but I guess we can do this.

Note for later: *Add second repository as temp remote. checkout current pr-branch, rebase --onto new base, push to new temp-remote and reopen PR against new repository. once pushed remove temp remote.*

**Comment by cordoval** [comment]
@mmoreram i can move the PR but i need assurance that we are moving all bamboo without sensiolabs extra framework bundle -> meaning no annotations there of that kind so moving to yml. Is this ok?

**Comment by mmoreram** [comment]
@cordoval Is the same package indeed, but we should remove all annotations from plugins. Is that okay for everyone? @elcodi/deciders

**Comment by cordoval** [comment]
I say let's do this /o/ :+1:

**Comment by cordoval** [comment]
bump @elcodi/deciders

**Comment by mmoreram** [comment]
Closing this PR, because it has to be moved to bamboo.

**Comment by cordoval** [comment]
@mmoreram i was waiting for a say on @elcodi/owners to decide, because if i move it and then it gets rejected it would have been in vain. Can you then please confirm me that I can do this and that it will not be rejected? I guess you have, just wanted to make sure.

**Comment by cordoval** [comment]
@mmoreram can you please confirm? thanks :+1:

**Comment by mmoreram** [comment]
@cordoval Good for me!

**Comment by cordoval** [comment]
@mmoreram done in https://github.com/elcodi/bamboo/pull/392

**Pull request closed without merging**
