### PR TITLE
Make country option mandatory for all command scripts

### PR DESCRIPTION
**Pull request by pramoddas**
1. Issue when command is executed "php app/console elcodi:locations:populate"
2. Made changes so that the above command throws an exception when --country  option is not specified...

### CODE REVIEW

**Comment by EmanueleMinotto** [comment]
please run the coding style tools ([ref](https://github.com/elcodi/elcodi/blob/master/CONTRIBUTING.md))

**Comment by mmoreram** [comment]
Thanks for that PR :D

This Exception should be thrown in all commands. @EmanueleMinotto are you agree?

@pramoddas please, style check should be applied :)

**Comment by EmanueleMinotto** [comment]
sure @mmoreram, imo something more specific than an `\InvalidArgumentException`, but still no idea what exactly

**Comment by mmoreram** [comment]
I'm afraid that an Exception will make people think that there is an issue with Elcodi, so maybe a message should be enough...

**Comment by mmoreram** [comment]
Closing in favor of https://github.com/elcodi/elcodi/pull/1069

**Pull request closed without merging**
