### PR TITLE
remove classes.yml

### PR DESCRIPTION
**Pull request by cordoval**
| Q | A |
| --- | --- |
| Bug Fix? | no |
| New Feature? | no |
| BC Breaks? | no |
| Deprecations? | no |
| Tests Pass? | no |
| Fixed Tickets | #270 |
| License | MIT |

### CODE REVIEW

**Comment by cordoval** [comment]
@mmoreram can i continue with this one?

**Comment by mmoreram** [comment]
@cordoval Yes, but first of all, rebase from master please :)

**Comment by mmoreram** [comment]
@cordoval And
* Remove all the `classes.yml` files
* Remove the reference to these classes inside Extension objects in Bundles
After that, it should work :)

**Comment by cordoval** [comment]
ok moving with this one

**Comment by cordoval** [comment]
bump @mmoreram

**Comment by mmoreram** [comment]
Well, references have no changed right? I mean, now you are accessing to non-existing parameters.

**Comment by cordoval** [comment]
yeah just saw that i will fix that now, thanks @mmoreram team effort

**Comment by mmoreram** [comment]
@cordoval ping me when is ready :dancer:

**Comment by cordoval** [comment]
@mmoreram i was trying to tell you something in the last 2 commits. Last time you guys told me that replacing all the .class parameters was wrong. If i don't do this everywhere then the tests will not pass. Can you please explain why you did not want to remove all the .class parameters?

**Comment by mmoreram** [comment]
@cordoval who told you not to remove them all?

* All .class references should be removed, but just the `elcodi.entity.*.class` should stay

**Comment by cordoval** [comment]
weird @mmoreram i cannot find %elcodi.adapter.menu_route_generator.dummy.class% defined anywhere, do you know where this is defined?

**Comment by hacfi** [comment]
@cordoval here: https://github.com/elcodi/elcodi/blob/master/src/Elcodi/Bundle/MenuBundle/Resources/config/routeGeneratorAdapters/dummyRouter.yml#L6

**Comment by cordoval** [comment]
i guess that class does not exist anywhere hmmm

**Comment by cordoval** [comment]
bump @mmoreram

**Comment by cordoval** [comment]
you told me to notify you @mmoreram  :+1:

**Comment by cordoval** [comment]
rebased @mmoreram

**Comment by mmoreram** [comment]
@cordoval Checking :D

**Comment by cordoval** [comment]
can you please run tests manually? @mmoreram

**Comment by mmoreram** [comment]
Yes :)

**Comment by cordoval** [comment]
rebased @mmoreram

**Comment by mmoreram** [comment]
@cordoval Tests are not passing in local...

**Comment by cordoval** [comment]
I can close because it was already merged right? @mmoreram ?

**Pull request closed without merging**
