### PR TITLE
Removed NullMoney and StubMoney

### PR DESCRIPTION
**Pull request by mmoreram**
* In order to simplify the model

### CODE REVIEW

**Comment by mmoreram** [comment]
Solves https://github.com/elcodi/elcodi/pull/653

Related to https://github.com/elcodi/elcodi/issues/292 as well

**Comment by mmoreram** [comment]
ping @elcodi/deciders

**Comment by xphere** [comment]
I think that `Money` should be rethought as a whole. But not for v1.0, so I'm :+1:

**Comment by alch** [comment]
Agree 100%

@xphere why do you think it should be rewritten'

**Comment by xphere** [comment]
I think it adds too many complexity for what it does, wrapping another `Money` library under the hood, moving back and forth between the two codebases. IMO, there has to be a simple way.

**Pull request merged**
